// <auto-generated />
using System;
using LibraryWebApp.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LibraryWebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("LibraryWebApp.Domain.Models.Booking", b =>
                {
                    b.Property<long>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long>("BookId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ReaderId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookingId");

                    b.HasIndex("ReaderId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("LibraryWebApp.Domain.Models.Favourite", b =>
                {
                    b.Property<long>("FavouriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long>("BookId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReaderId")
                        .HasColumnType("bigint");

                    b.HasKey("FavouriteId");

                    b.HasIndex("ReaderId");

                    b.ToTable("Favourites");
                });

            modelBuilder.Entity("LibraryWebApp.Domain.Models.Reader", b =>
                {
                    b.Property<long>("ReaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberCC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReaderId");

                    b.ToTable("Reader");
                });

            modelBuilder.Entity("LibraryWebApp.Domain.Models.Booking", b =>
                {
                    b.HasOne("LibraryWebApp.Domain.Models.Reader", "Reader")
                        .WithMany("Bookings")
                        .HasForeignKey("ReaderId");

                    b.Navigation("Reader");
                });

            modelBuilder.Entity("LibraryWebApp.Domain.Models.Favourite", b =>
                {
                    b.HasOne("LibraryWebApp.Domain.Models.Reader", "Reader")
                        .WithMany("Favourites")
                        .HasForeignKey("ReaderId");

                    b.Navigation("Reader");
                });

            modelBuilder.Entity("LibraryWebApp.Domain.Models.Reader", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Favourites");
                });
#pragma warning restore 612, 618
        }
    }
}
